language: python

python:
  - 2.6
  - 2.7

env:

install:
  - pip install -r requirements.txt

script:
  - nosetests --with-cover --cover-package requests_panel requests_panel

after_success: coveralls